### ISSUE TITLE
raw RSS link broken

### ISSUE THREAD

**Issue by compwron** [superfeedr/subtome#80]
raw RSS feed link on http://www.theatermania.com/rss/ is broken (links to ``https://www.subtome.com/#/redirect?to={feed}`` )

**Comment by julien51** [comment]
Hum, could you clarify?
When I click on any of the links on http://www.theatermania.com/rss/, I see the Subtome modal just fine, and then I can click on he "RSS feed" icon and be redirected to the actual feed as expected.

**Comment by julien51** [comment]
Any progress on this?

**Comment by compwron** [comment]
Hmm it works for me now too. Maybe it was a config issue on their end. I should have gotten a screenshot. Sorry

**Comment by compwron** [comment]
Maybe I have a local issue but I'm not sure how to tell. Here are some screenshots. Thanks!

![screen shot 2015-06-07 at 8 08 13 pm](https://cloud.githubusercontent.com/assets/578159/8027678/01715d68-0d51-11e5-839d-0df9aea7e61e.png)

![screen shot 2015-06-07 at 8 08 25 pm](https://cloud.githubusercontent.com/assets/578159/8027677/0169a8ca-0d51-11e5-855a-3222f2a4b0a8.png)

![screen shot 2015-06-07 at 8 08 31 pm](https://cloud.githubusercontent.com/assets/578159/8027676/0150e13c-0d51-11e5-92f1-7d837684b5e6.png)

**Comment by julien51** [comment]
Thanks! On which button do you click to get from the last but one screenshot to the last one?

**Comment by compwron** [comment]
The bottommost link that says "RSS Feed"

**Comment by julien51** [comment]
This is really strange, because when I do the same, I'm redirected to the feed's page: http://www.theatermania.com/rss.xml

I'm also using Firefox (38.0.5) and I tried from Chrome, and Safari and they all redirect me to the feed as expected...

Is there any message in the console of your browser?

**Comment by compwron** [comment]
I just tried to replicate again and it totally works without error now. (redirects to http://www.theatermania.com/rss.xml )

I suspect that it was a configuration error by theatermania somehow, but I'm really not sure. Anyway, I'll close the ticket. Thanks for looking into it!
