### ISSUE TITLE
docs: publishers: empty tag

### ISSUE THREAD

**Issue by cweiske** [superfeedr/subtome#81]
http://docs.subtome.com/publishers/ has a sentence in which something seems to be missing:

> as well as any feed placed in the section.

![screenshot](http://fotostore.cweiske.de/screenshots/2015-07-06%20subtome%20publishers%20bug.png)

**Comment by julien51** [comment]
Thanks @cweiske! Fixing it now :) (escaping problem with Jekyll!)
