### ISSUE TITLE
Allow multiple subtome buttons on one page

### ISSUE THREAD

**Issue by singpolyma** [superfeedr/subtome#88]
Right now the code detects the feed to be the current page, or looks for a subtome button on the page and uses the data- attributes... but if I have multiple buttons this will not work.

**Comment by julien51** [comment]
Ha! Indeed, the button can be customized in any way you want though so you can add multiple buttons to a single page... Please, [see the docs](http://docs.subtome.com/publishers/).

**Comment by singpolyma** [comment]
Ok, I'll try it again, but looking at the code I'm not sure how this is possible... the code is never told what button was pushed or anything at all...

**Comment by singpolyma** [comment]
re-read the code and think I found what I was doing wrong. sorry for the noise

**Comment by julien51** [comment]
Ha! Well, happy this is resolved :) if you can think of anything we can do to make the docs more obvious, please, let me know!

**Comment by singpolyma** [comment]
The docs specifically say the the obfuscated snippet loads a particular js file. But do not mention that it also assigns the button onto a global variable that said script expects.
